### ISSUE TITLE
getCurrentGameBySummonerId 404

### ISSUE THREAD

**Issue by joeflateau** [Pupix/lol-riot-api-module#2]
This method always 404s for me, even for summoners in matches. 

I fixed by calling XP.upperCase on the platformId in doRequest.value.

Would you like a pull request?

**Comment by Pupix** [comment]
Thanks for this. I [already fixed](https://github.com/Pupix/lol-riot-api-module/commit/ebc9a791a3fb420e922a641c0a2867c3dcb6dfde) in master. A new version release will come in the following days, after I add the tournament API aswell. Meanwhile you can either use your local copy or download the master.

Cheers.

**Comment by joeflateau** [comment]
Great thanks!
