### ISSUE TITLE
expandjs 1.X

### ISSUE THREAD

**Issue by danielsogl** [Pupix/lol-riot-api-module#6]
Is it possible to update to the latest expandjs release? I'm not really in that library so maybe you can do that for me. 

I only have problems with the removed merge and forEach method.

**Comment by Pupix** [comment]
Updated expand.js and xp-request to 1.1.0.

Only `forEach` was removed in favor of the native `Array.prototype.forEach`, `merge` is still there.

**Comment by danielsogl** [comment]
Ahhh ^^ Thank you!
